name: see_v
description: A new Flutter project

environment:
  sdk: '^3.1.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/logofinal.png
    - assets/cv example1.webp
    - assets/cvexample2.webp
    - assets/UPDATE.png
    - assets/updateimage.png
    - assets/homeimage.png
